### ISSUE TITLE
Policy field `users` ignored if it's not a YAML string

### ISSUE THREAD

**Issue by dekimir** [chiselstrike/chiselstrike#1638]
When a [user-restricting policy](https://docs.chiselstrike.com/InDepth/pol#policies-for-logged-in-users) is defined in YAML, but the `users:` key is something other than a string, the policy gets ignored.  The following policies, for instance, are parsed without error but don't restrict endpoint access at all:
```yaml
endpoints:
  - path: /
    users:
      - a: 1
      - b: 2
  - path: /hello
    users: 123.
```
The first `users:` should be rejected with an error message, while the second should restrict access unless the user matches `123.`.
